### PR TITLE
Initital code, with full implementation of swerve

### PR DESCRIPTION
**Pull request by noah4546**
- WPILib command based code.
- Swerve Drive
- Swerve Teleop
- 2 Basic Sweve Autos

### CODE REVIEW

**Review by Stevon2386 — APPROVED** [review]
Looks good

**Review by Timatoot — APPROVED** [review]
Good

**Review by 10tothe6 — APPROVED** [review]
code looks good

**Review by Stevon2386 — CHANGES_REQUESTED** [review]
Fix your code

**Review by Stevon2386 — APPROVED** [review]

**Pull request merged**
